name: run_linux

on:
  repository_dispatch:
    types: [ci-linux-*]

jobs:
  test:
    strategy:
      matrix:
        envinfo:
          - { name: 'linux-3.6-x64', os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }

    env:
        GITHUB_WORKFLOW: ${{ matrix.envinfo.name }}

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: Format ci flag file name
      shell: bash
      run: |
        echo "::set-env name=FLAG_FILE::$(echo ${{ github.event.client_payload.sha }})-ci-linux"

    - name: Setup AWS S3 dist path
      shell: bash
      run: |
        echo "::set-env name=DIST_DIR::dist/tqsdk-python-private/$(echo ${{ github.event.client_payload.ref }}#refs/heads/)/$(date -d today +%Y%m%d)_$(echo ${{ github.event.client_payload.sha }})/"
        echo "::set-env name=DOC_DIR::docs/tqsdk-python/$(echo ${{ github.event.client_payload.ref }}#refs/heads/)/"

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        touch ${{ github.event.client_payload.sha }}-ci-win
        echo "$GITHUB_CONTEXT"
        echo ${{ github.run_id }}

