name: run_linux

on:
  repository_dispatch:
    types: [aexec-ci-*]

jobs:
  test:
    strategy:
      matrix:
        envinfo:
          - { name: 'linux-3.6-x64', os: windows-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }

    env:
        GITHUB_WORKFLOW: ${{ matrix.envinfo.name }}

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        body-includes:  ${{ github.event.client_payload.sha }} and ${{ matrix.envinfo.os }}

    - name: Update comment
      if: ${{ steps.fc.outputs.comment-id }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          - **[ √ ] ${{ matrix.envinfo.os }}:** Run ci success