name: run_win

on:
  repository_dispatch:
    types: [ci-win-*]

jobs:
  test:
    strategy:
      matrix:
        envinfo:
          - { name: 'linux-3.6-x64', os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }

    env:
        GITHUB_WORKFLOW: ${{ matrix.envinfo.name }}

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: exec shell
      run: |
        pwd
        ls -lrt
        echo "${GITHUB_WORKFLOW}"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: shinny-hongyan/repo-ci-dispatch-private
        ref: ${{ github.event.client_payload.ref }}
        token: ${{ secrets.GH_PERSONAL_TOKEN }}

    - name: exec shell
      run: |
        pwd
        ls -lrt
        echo ${{ github.event.client_payload.ref }}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: echo job status
      run: |
        echo ${{ job.status }}
        exit 1

    - name: Find Comment
      if: always() and ${{ github.event.client_payload.pr_flag }}
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        repository: shinny-hongyan/repo-ci-dispatch-private
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        issue-number: ${{ github.event.client_payload.pr_number }}
        body-includes:  'This is the ci result'

    - name: Update comment
      if: failed() and ${{ github.event.client_payload.pr }} and ${{ steps.fc.outputs.comment-id }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        repository: shinny-hongyan/repo-ci-dispatch-private
        issue-number: ${{ github.event.client_payload.pr_number }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          - **[ × ] ci-win:** Run ci failed