name: run_linux

on:
  repository_dispatch:
    types: [ci-linux-*]

jobs:
  test:
    strategy:
      matrix:
        envinfo:
          - { name: 'linux-3.6-x64', os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }

    env:
        GITHUB_WORKFLOW: ${{ matrix.envinfo.name }}

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: exec shell
      run: |
        pwd
        ls -lrt
        echo "${GITHUB_WORKFLOW}"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: shinny-hongyan/repo-ci-dispatch-private
        ref: ${{ github.event.client_payload.ref }}
        token: ${{ secrets.GH_PERSONAL_TOKEN }}

    - name: exec shell
      run: |
        pwd
        ls -lrt
        echo ${{ github.event.client_payload.ref }}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: echo job status
      run: |
        echo ${{ job.status }}
        exit 1

    - name: Create commit comment
      if: ${{ success() }} and ${{ github.event.client_payload.pr }}
      uses: peter-evans/commit-comment@v1
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        repository: shinny-hongyan/repo-ci-dispatch-private
        sha: ${{ github.event.client_payload.pr }}
        body: ${{ github.event.client_payload.title }} run ci success on linux platform
        position: 1