name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          touch job1.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: job1.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
    - shell: bash
      run: |
        touch job2.txt
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v2
      with:
        name: homework
        path: job2.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: homework

      - name: Print the final result
        shell: bash
        run: |
          touch job3.txt
          ls -lrt