name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    strategy:
      matrix:
        envinfo:
          - { name: 'windows-3.6-x64', os: windows-latest, bdist-platform: 'win_amd64' }
          - { name: 'windows-3.6-x86', os: windows-latest, bdist-platform: 'win32' }

    runs-on: ${{ matrix.envinfo.os }}
    steps:
      - shell: bash
        run: |
          mkdir dist
          cd dist
          touch ${{ matrix.envinfo.bdist-platform }}.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: dist/${{ matrix.envinfo.bdist-platform }}.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
    - shell: bash
      run: |
        mkdir dist
        cd dist
        touch job2.txt
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v2
      with:
        name: homework
        path: dist/job2.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: homework
          path: ./dist

      - name: Print the final result
        shell: bash
        run: |
          touch job3.txt
          ls -lrt
          cd dist
          ls -lrt