name: dispatch task

on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump GitHub context
      uses: shinny-hongyan/trigger-workflow-and-wait@master
      with:
        owner: shinny-hongyan
        repo: repo-ci-dispatch
        github_token: ${{ secrets.GH_PERSONAL_TOKEN }}
        event-type: exec-ci-${{ github.event.head_commit.message }}
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    
    - name: echo
      run: echo "run finished"