name: dispatch task

on: [push]

jobs:
  test:
    strategy:
      matrix:
        envinfo:
          - { name: 'linux-3.6-x64', os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }
          - { name: 'linux-3.7-x64', os: ubuntu-latest, python-version: 3.7.x, python-arch: x64, TZ: 'Asia/Shanghai' }

    env:
        PYTHONIOENCODING: "utf-8"
        PYTHONHASHSEED: 32
        TZ: ${{ matrix.envinfo.TZ }}
        TESTLOGPATH: "./log_archive/"
        TESTLOGNAME: ${{ matrix.envinfo.name }}

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: echo result
      run: echo "halo"

  summary:
    name: summary CI result
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: failed
        if: failed()
        shell: bash
        run: |
          echo "failed"

      - name: success
        if: success()
        shell: bash
        run: |
          echo "success"