name: dispatch task

on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"


    - uses: convictional/trigger-workflow-and-wait
      with:
        owner: shinny-hongyan
        repo: repo-ci-dispatch
        github_token: ${{ secrets.GH_PERSONAL_TOKEN }}
        wait_interval: 60
        event-type: exec-ci-${{ github.event.head_commit.message }}

    - name: Invoke workflow
      run: echo "run all success"