name: dispatch task

on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Invoke workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        event-type: exec-ci-${{ github.event.head_commit.message }}
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'