name: dispatch task

on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        issue-number: 1
        body-includes:  'This is the ci result'

    - name: echo job status
      run: |
        echo ${{ steps.fc.outputs.comment-id }}

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        issue-number: 1
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          This is the ci result, see: https://github.com/shinny-hongyan/repo-ci-dispatch/actions :sparkles:

    - name: Invoke workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        event-type: exec-ci-${{ github.event.head_commit.message }}
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'