name: Dispatch

on:
  repository_dispatch:
    types: [ci-run]

jobs:
  test:
    strategy:
      matrix:
        ci_env: ['ci-linux', 'ci-win']

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Invoke workflow
      uses: peter-evans/repository-dispatch@v1 
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        repository: shinny-hongyan/repo-ci-dispatch
        event-type: ${{ matrix.ci_env }}-${{ github.event.client_payload.title }}
        client-payload: '{"ref": "${{ github.event.client_payload.ref }}", 
        "sha": "${{ github.event.client_payload.sha }}", 
        "title": "${{ github.event.client_payload.title }}", 
        "pr_flag": "${{ github.event.client_payload.pr_flag }}", 
        "pr": "${{ github.event.client_payload.pr }}", 
        "pr_number": "${{ github.event.client_payload.pr_number }}" }'


  summary:
    name: summary CI result
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: jitterbit/await-check-suites@v1
      with:
        repository: shinny-hongyan/repo-ci-dispatch
        ref: ${{ github.sha }}
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        onlyFirstCheckSuite: true

    - name: Find Comment
      if: success() && github.event_name == 'pull_request'
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        repository: shinny-hongyan/repo-ci-dispatch-private
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body-includes:  'This is the ci result'

    - name: Add comment for ci success
      if: success() && steps.fc.outputs.comment-id == '' && github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        repository: shinny-hongyan/repo-ci-dispatch-private
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          All CI run success!
        reactions: '+1'
