name: run_linux

on:
  repository_dispatch:
    types: [run-ci-*]

jobs:
  setup:
    name: log the workflow url in src repo
    runs-on: ubuntu-latest
    steps:
    - name: Add comment show workflow url
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        repository: shinny-hongyan/repo-ci-dispatch-private
        issue-number: ${{ github.event.client_payload.pr_number }}
        comment-id: ${{ github.event.client_payload.pr_number.comment_id }}
        body: |
          Workflow url: 'https://github.com/shinny-hongyan/repo-ci-dispatch/actions/runs/'${{ github.run_id }}

  run:
    needs: setup
    strategy:
      matrix:
        envinfo:
          - { name: 'linux-3.6-x64', os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }
          - { name: 'windows-3.6-x64', os: windows-latest, python-version: 3.6.x, python-arch: x64, TZ: 'CST-8' }

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  summary:
    name: summary CI result
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Add comment show success
      if: github.event.client_payload.pr_flag == 'true'
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        repository: shinny-hongyan/repo-ci-dispatch-private
        issue-number: ${{ github.event.client_payload.pr_number }}
        comment-id: ${{ github.event.client_payload.pr_number.comment_id }}
        body: |
          All CI run success!
        reactions: '+1'