name: run_linux

on: [push]

jobs:
  test:
    strategy:
      matrix:
        envinfo:
          - { name: 'linux-3.6-x64', os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }
          - { name: 'windows-3.6-x64', os: windows-latest, python-version: 3.6.x, python-arch: x64, TZ: 'CST-8' }

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        exit 1

    - name: Log failed info
      if: failure()
      run: |
        echo ${{ github.run_id }} > ${{ matrix.envinfo.os }}.flag.txt
        cat ${{ matrix.envinfo.os }}.flag.txt

    - name: Upload a file when jobs failed
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: ci-result
        path: ${{ matrix.envinfo.os }}.flag.txt

  summary:
    name: summary CI result
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Download ci-result
      if: always()
      uses: actions/download-artifact@v1
      with:
        name: ci-result

    - name: Print the final result
      if: always()
      shell: bash
      run: |
        value=`ls -lrt ci-result`
        echo The result is $value