name: run_linux

on:
  repository_dispatch:
    types: [run-ci-*]

jobs:
  setup:
    name: log the workflow url in src repo
    runs-on: ubuntu-latest
    steps:
    - name: Add comment show workflow url
      uses: peter-evans/create-or-update-comment@v1
      id: comment
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        repository: shinny-hongyan/repo-ci-dispatch-private
        issue-number: ${{ github.event.client_payload.pr_number }}
        comment-id: ${{ github.event.client_payload.comment_id }}
        body: |
          - Workflow url: https://github.com/shinny-hongyan/repo-ci-dispatch/actions/runs/${{ github.run_id }}

    - name: Setup AWS S3 dist path
      shell: bash
      run: |
        echo "::set-env name=DIST_DIR::dist/tqsdk-python-private/$(echo ${{ github.event.client_payload.ref}})/$(date -d today +%Y%m%d)_$(echo ${{ github.event.client_payload.sha }})/"
        echo "::set-env name=DOC_DIR::docs/tqsdk-python/$(echo ${{ github.event.client_payload.ref }#refs/heads/})/"

    - name: echo comment-id
      if: steps.comment.outputs.comment-id != ''
      run: |
        echo "::set-env name=COMMENT_ID::${{ steps.comment.outputs.comment-id }}"

  run:
    needs: setup
    strategy:
      matrix:
        envinfo:
          - { name: 'linux-3.6-x64', os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }
          - { name: 'windows-3.6-x64', os: windows-latest, python-version: 3.6.x, python-arch: x64, TZ: 'CST-8' }

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  summary:
    name: summary CI result
    needs: run
    runs-on: ubuntu-latest
    steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        repository: shinny-hongyan/repo-ci-dispatch-private
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        issue-number: ${{ github.event.client_payload.pr_number }}
        body-includes:  https://github.com/shinny-hongyan/repo-ci-dispatch/actions/runs/${{ github.run_id }}

    - name: Add comment show success
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
        repository: shinny-hongyan/repo-ci-dispatch-private
        issue-number: ${{ github.event.client_payload.pr_number }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          workflow ${{ github.run_id }} run success!
        reactions: '+1'
